//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentApiV2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Araba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Araba()
        {
            this.Kayit = new HashSet<Kayit>();
        }
    
        public string carId { get; set; }
        public string carMarka { get; set; }
        public string carModel { get; set; }
        public string carYakit { get; set; }
        public string carYolcu { get; set; }
        public string carKatId { get; set; }
        public string carFiyat { get; set; }
        public string carTelNo { get; set; }
        public byte[] carImg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kayit> Kayit { get; set; }
    }
}
