//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentApiV2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayit
    {
        public string kayId { get; set; }
        public string kayCarId { get; set; }
        public string kayKatId { get; set; }
    
        public virtual Araba Araba { get; set; }
        public virtual Kategori Kategori { get; set; }
    }
}
