//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentApiV2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public string userId { get; set; }
        public string userAdi { get; set; }
        public string userMail { get; set; }
        public string userPassword { get; set; }
        public string userIsAdmin { get; set; }
        public byte[] userImage { get; set; }
    }
}
